# 1. Import library yang diperlukan

In [1]:
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori, association_rules
from mlxtend.preprocessing import TransactionEncoder

# 2. Import dataset

#### Sumber Dataset : https://www.kaggle.com/shazadudwadia/supermarket

In [2]:
df = pd.read_csv("D:\Kuliah\Semester_5\Machine Learning\datasets\GroceryStoreDataSet.csv", names=['products'], sep=',')
df.head()

                        products
0             MILK,BREAD,BISCUIT
1  BREAD,MILK,BISCUIT,CORNFLAKES
2            BREAD,TEA,BOURNVITA
3           JAM,MAGGI,BREAD,MILK
4              MAGGI,TEA,BISCUIT

In [3]:
df.shape

(20, 1)

# 3. Membagi produk kemudian memasukkan ke dalam list "data"

In [4]:
data = list(df["products"].apply(lambda x:x.split(",")))
data

[['MILK', 'BREAD', 'BISCUIT'],
 ['BREAD', 'MILK', 'BISCUIT', 'CORNFLAKES'],
 ['BREAD', 'TEA', 'BOURNVITA'],
 ['JAM', 'MAGGI', 'BREAD', 'MILK'],
 ['MAGGI', 'TEA', 'BISCUIT'],
 ['BREAD', 'TEA', 'BOURNVITA'],
 ['MAGGI', 'TEA', 'CORNFLAKES'],
 ['MAGGI', 'BREAD', 'TEA', 'BISCUIT'],
 ['JAM', 'MAGGI', 'BREAD', 'TEA'],
 ['BREAD', 'MILK'],
 ['COFFEE', 'COCK', 'BISCUIT', 'CORNFLAKES'],
 ['COFFEE', 'COCK', 'BISCUIT', 'CORNFLAKES'],
 ['COFFEE', 'SUGER', 'BOURNVITA'],
 ['BREAD', 'COFFEE', 'COCK'],
 ['BREAD', 'SUGER', 'BISCUIT'],
 ['COFFEE', 'SUGER', 'CORNFLAKES'],
 ['BREAD', 'SUGER', 'BOURNVITA'],
 ['BREAD', 'COFFEE', 'SUGER'],
 ['BREAD', 'COFFEE', 'SUGER'],
 ['TEA', 'MILK', 'COFFEE', 'CORNFLAKES']]

# 4. Algoritma Apriori dan Encoding One-Hot

#### Algoritma Apriori untuk mengubah True/False menjadi 1/0. Menggunakan TransactionEncoder, kita konversi daftar menjadi daftar Boolean terenkode. Produk yang dibeli atau tidak dibeli pelanggan selama berbelanja sekarang akan diwakili oleh nilai 1 dan 0.

In [5]:
a = TransactionEncoder()
a_data = a.fit(data).transform(data)
df = pd.DataFrame(a_data, columns = a.columns_)
df = df.replace(False, 0)
df = df.replace(True, 1)
df

,BISCUIT,BOURNVITA,BREAD,COCK,COFFEE,CORNFLAKES,JAM,MAGGI,MILK,SUGER,TEA
0,1,0,1,0,0,0,0,0,1,0,0
1,1,0,1,0,0,1,0,0,1,0,0
2,0,1,1,0,0,0,0,0,0,0,1
3,0,0,1,0,0,0,1,1,1,0,0
4,1,0,0,0,0,0,0,1,0,0,1
5,0,1,1,0,0,0,0,0,0,0,1
6,0,0,0,0,0,1,0,1,0,0,1
7,1,0,1,0,0,0,0,1,0,0,1
8,0,0,1,0,0,0,1,1,0,0,1
9,0,0,1,0,0,0,0,0,1,0,0
10,1,0,0,1,1,1,0,0,0,0,0
11,1,0,0,1,1,1,0,0,0,0,0
12,0,1,0,0,1,0,0,0,0,1,0
13,0,0,1,1,1,0,0,0,0,0,0
14,1,0,1,0,0,0,0,0,0,1,0
15,0,0,0,0,1,1,0,0,0,1,0
16,0,1,1,0,0,0,0,0,0,1,0
17,0,0,1,0,1,0,0,0,0,1,0
18,0,0,1,0,1,0,0,0,0,1,0
19,0,0,0,0,1,1,0,0,1,0,1

# 5. Menerapkan Apriori dan Menampilkan Hasilnya

#### Langkah selanjutnya adalah membuat Model Apriori. Kita dapat mengubah semua parameter dalam Model Apriori dengan package mlxtend. Saya akan mencoba menggunakan parameter min_support untuk pemodelan ini. Untuk ini, saya menetapkan nilai min_support dengan nilai ambang 10%.

In [6]:
df = apriori(df, min_support = 0.1, use_colnames = True, verbose = 1)
df

Processing 108 combinations | Sampling itemset size 4

    support                             itemsets
0      0.35                            (BISCUIT)
1      0.20                          (BOURNVITA)
2      0.65                              (BREAD)
3      0.15                               (COCK)
4      0.40                             (COFFEE)
5      0.30                         (CORNFLAKES)
6      0.10                                (JAM)
7      0.25                              (MAGGI)
8      0.25                               (MILK)
9      0.30                              (SUGER)
10     0.35                                (TEA)
11     0.20                     (BISCUIT, BREAD)
12     0.10                      (BISCUIT, COCK)
13     0.10                    (BISCUIT, COFFEE)
14     0.15                (BISCUIT, CORNFLAKES)
15     0.10                     (BISCUIT, MAGGI)
16     0.10                      (BISCUIT, MILK)
17     0.10                       (BISCUIT, TEA)
18     0.15                   (BREAD, BOURNVITA)
19     0.10                   (SUGER, BOURNVITA)
20     0.10                     (TEA, BOURNVITA)
21     0.15                      (BREAD, COFFEE)
22     0.10                         (BREAD, JAM)
23     0.15                       (MAGGI, BREAD)
24     0.20                        (MILK, BREAD)
25     0.20                       (SUGER, BREAD)
26     0.20                         (BREAD, TEA)
27     0.15                       (COCK, COFFEE)
28     0.10                   (COCK, CORNFLAKES)
29     0.20                 (CORNFLAKES, COFFEE)
30     0.20                      (SUGER, COFFEE)
31     0.10                   (MILK, CORNFLAKES)
32     0.10                    (TEA, CORNFLAKES)
33     0.10                         (MAGGI, JAM)
34     0.20                         (MAGGI, TEA)
35     0.10               (BISCUIT, MILK, BREAD)
36     0.10              (BISCUIT, COCK, COFFEE)
37     0.10          (BISCUIT, COCK, CORNFLAKES)
38     0.10        (BISCUIT, CORNFLAKES, COFFEE)
39     0.10                (BISCUIT, MAGGI, TEA)
40     0.10              (BREAD, TEA, BOURNVITA)
41     0.10               (SUGER, BREAD, COFFEE)
42     0.10                  (MAGGI, BREAD, JAM)
43     0.10                  (MAGGI, BREAD, TEA)
44     0.10           (COCK, CORNFLAKES, COFFEE)
45     0.10  (BISCUIT, COCK, CORNFLAKES, COFFEE)

# 6. Menampilkan Support, Confidence, & Lift

### Saya memilih nilai Confidence minimum sebanyak 60%. Dengan kata lain, ketika produk X dibeli, kita dapat mengatakan bahwa pembelian produk Y adalah 60% atau lebih.

In [7]:
df_ar = association_rules(df, metric = "confidence", min_threshold = 0.6)
df_ar

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(COCK),(BISCUIT),0.15,0.35,0.10,0.666667,1.904762,0.0475,1.950
1,(BOURNVITA),(BREAD),0.20,0.65,0.15,0.750000,1.153846,0.0200,1.400
2,(JAM),(BREAD),0.10,0.65,0.10,1.000000,1.538462,0.0350,inf
3,(MAGGI),(BREAD),0.25,0.65,0.15,0.600000,0.923077,-0.0125,0.875
4,(MILK),(BREAD),0.25,0.65,0.20,0.800000,1.230769,0.0375,1.750
5,(SUGER),(BREAD),0.30,0.65,0.20,0.666667,1.025641,0.0050,1.050
6,(COCK),(COFFEE),0.15,0.40,0.15,1.000000,2.500000,0.0900,inf
7,(COCK),(CORNFLAKES),0.15,0.30,0.10,0.666667,2.222222,0.0550,2.100
8,(CORNFLAKES),(COFFEE),0.30,0.40,0.20,0.666667,1.666667,0.0800,1.800
9,(SUGER),(COFFEE),0.30,0.40,0.20,0.666667,1.666667,0.0800,1.800
10,(JAM),(MAGGI),0.10,0.25,0.10,1.000000,4.000000,0.0750,inf
11,(MAGGI),(TEA),0.25,0.35,0.20,0.800000,2.285714,0.1125,3.250
12,"(BISCUIT, MILK)",(BREAD),0.10,0.65,0.10,1.000000,1.538462,0.0350,inf
13,"(BISCUIT, COCK)",(COFFEE),0.10,0.40,0.10,1.000000,2.500000,0.0600,inf
14,"(BISCUIT, COFFEE)",(COCK),0.10,0.15,0.10,1.000000,6.666667,0.0850,inf
15,"(COCK, COFFEE)",(BISCUIT),0.15,0.35,0.10,0.666667,1.904762,0.0475,1.950
16,(COCK),"(BISCUIT, COFFEE)",0.15,0.10,0.10,0.666667,6.666667,0.0850,2.700
17,"(BISCUIT, COCK)",(CORNFLAKES),0.10,0.30,0.10,1.000000,3.333333,0.0700,inf
18,"(BISCUIT, CORNFLAKES)",(COCK),0.15,0.15,0.10,0.666667,4.444444,0.0775,2.550
19,"(COCK, CORNFLAKES)",(BISCUIT),0.10,0.35,0.10,1.000000,2.857143,0.0650,inf
20,(COCK),"(BISCUIT, CORNFLAKES)",0.15,0.15,0.10,0.666667,4.444444,0.0775,2.550
21,"(BISCUIT, CORNFLAKES)",(COFFEE),0.15,0.40,0.10,0.666667,1.666667,0.0400,1.800
22,"(BISCUIT, COFFEE)",(CORNFLAKES),0.10,0.30,0.10,1.000000,3.333333,0.0700,inf
23,"(BISCUIT, MAGGI)",(TEA),0.10,0.35,0.10,1.000000,2.857143,0.0650,inf
24,"(BISCUIT, TEA)",(MAGGI),0.10,0.25,0.10,1.000000,4.000000,0.0750,inf
25,"(BREAD, BOURNVITA)",(TEA),0.15,0.35,0.10,0.666667,1.904762,0.0475,1.950
26,"(TEA, BOURNVITA)",(BREAD),0.10,0.65,0.10,1.000000,1.538462,0.0350,inf
27,"(BREAD, COFFEE)",(SUGER),0.15,0.30,0.10,0.666667,2.222222,0.0550,2.100
28,"(MAGGI, BREAD)",(JAM),0.15,0.10,0.10,0.666667,6.666667,0.0850,2.700
29,"(MAGGI, JAM)",(BREAD),0.10,0.65,0.10,1.000000,1.538462,0.0350,inf
30,"(BREAD, JAM)",(MAGGI),0.10,0.25,0.10,1.000000,4.000000,0.0750,inf
31,(JAM),"(MAGGI, BREAD)",0.10,0.15,0.10,1.000000,6.666667,0.0850,inf
32,"(MAGGI, BREAD)",(TEA),0.15,0.35,0.10,0.666667,1.904762,0.0475,1.950
33,"(COCK, CORNFLAKES)",(COFFEE),0.10,0.40,0.10,1.000000,2.500000,0.0600,inf
34,"(COCK, COFFEE)",(CORNFLAKES),0.15,0.30,0.10,0.666667,2.222222,0.0550,2.100
35,(COCK),"(CORNFLAKES, COFFEE)",0.15,0.20,0.10,0.666667,3.333333,0.0700,2.400
36,"(BISCUIT, COCK, CORNFLAKES)",(COFFEE),0.10,0.40,0.10,1.000000,2.500000,0.0600,inf
37,"(BISCUIT, COCK, COFFEE)",(CORNFLAKES),0.10,0.30,0.10,1.000000,3.333333,0.0700,inf
38,"(BISCUIT, CORNFLAKES, COFFEE)",(COCK),0.10,0.15,0.10,1.000000,6.666667,0.0850,inf
39,"(COCK, CORNFLAKES, COFFEE)",(BISCUIT),0.10,0.35,0.10,1.000000,2.857143,0.0650,inf
40,"(BISCUIT, COCK)","(CORNFLAKES, COFFEE)",0.10,0.20,0.10,1.000000,5.000000,0.0800,inf
41,"(BISCUIT, CORNFLAKES)","(COCK, COFFEE)",0.15,0.15,0.10,0.666667,4.444444,0.0775,2.550
42,"(BISCUIT, COFFEE)","(COCK, CORNFLAKES)",0.10,0.10,0.10,1.000000,10.000000,0.0900,inf
43,"(COCK, CORNFLAKES)","(BISCUIT, COFFEE)",0.10,0.10,0.10,1.000000,10.000000,0.0900,inf
44,"(COCK, COFFEE)","(BISCUIT, CORNFLAKES)",0.15,0.15,0.10,0.666667,4.444444,0.0775,2.550
45,(COCK),"(BISCUIT, CORNFLAKES, COFFEE)",0.15,0.10,0.10,0.666667,6.666667,0.0850,2.700